name: rabpro
channels:
  - conda-forge
dependencies:
  - python=3.9
  - gdal
  - numpy
  - geopandas
  - scikit-image  
  - pyproj>2.2.0
  - shapely=2
  - requests
  - appdirs
  - earthengine-api
  - gdown
  - tqdm
  - beautifulsoup4
