{% set name = "rabpro" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jsta/rabpro/archive/v{{ version }}.tar.gz
  sha256: 1243ec81596aa3386c06144cbd981b5ebfbab5d1c6ad3fad37ded2d8a1e6979f
  # sha256 is the preferred checksum -- you can get it for a file with:
  #  `openssl sha256 <file name>`.  

build:
  noarch: python
  number: 0  
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:  
  host:
    - pip
    - python>=3.7,<3.10
    
  
  run:
    - numpy
    - geopandas>=0.7.0
    - scikit-image    
    - pyproj
    - shapely
    - requests
    - appdirs
    - tqdm
    - colorama
    - py-opencv
    - beautifulsoup4

test:  
  imports:
  - rabpro

about:
  home: https://github.com/VeinsOfTheEarth/rabpro  
  license: BSD  
  license_family: BSD  
  license_file: LICENSE.txt
  summary: 'Package to delineate subbasins and compute statistics.'  
  description: |
    rabpro computes longitudinal river profiles,
    global watershed delineation, watershed stats.    
  doc_url: https://veinsoftheearth.github.io/rabpro
  dev_url: https://github.com/VeinsOfTheEarth/rabpro
extra:
  recipe-maintainers:    
    - jsta
    - jonschwenk