name: Add comment
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'data request'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@3383acd359705b10cb1eeef05c0e88c056ea4666
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for your request! Maintainers can take the following steps to accept it:
            * [ ] upload to GEE with `rabpro.utils.upload_gee_tif_asset` (no spaces or extra periods are allowed in tif file pathing)            
            * [ ] add an entry to [Data/user_gee_datasets.json](../tree/main/Data/user_gee_datasets.json)
            * [ ] test with `rabpro.basin_stats.compute`