name: docs
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "rabpro/**"
      - "docs/**"
  pull_request:
    paths:
      - "rabpro/**"
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pandoc
        run: |
          sudo apt-get install -y --no-install-recommends pandoc

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docs/doc_requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/doc_requirements.txt

      - name: Build documentation
        run: cd docs && make html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          branch: gh-pages
          folder: docs/_build/html
