name: test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout
      - uses: actions/checkout@v2
      # Builds the package using the standard configuration
      - name: test
      - uses: cascode-labs/build-conda-action/action.yml@v0