name: test
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: conda-build
        uses: cascode-labs/build-conda-action@v0.1.4